---
- name: Setup MySQL Master with GTID Replication
  hosts: mysql_master
  become: yes
  vars:
    mysql_root_password: "YourStrongPassword"  # Установите здесь ваш пароль для root
    replication_user: "repl_user"
    replication_password: "repl_password"
    percona_repo_url: "http://www.percona.com/downloads/percona-release/redhat/0.1-6/percona-release-0.1-6.noarch.rpm"
    dump_file: "/path/to/bet.dmp"  # Укажите путь к вашему дампу

  tasks:
    - name: Install Percona repository
      yum:
        name: "{{ percona_repo_url }}"
        state: present

    - name: Install Percona Server
      yum:
        name: Percona-Server-server-57
        state: present

    - name: Copy custom MySQL configuration files
      copy:
        src: conf.d/
        dest: /etc/my.cnf.d/
        owner: root
        group: root
        mode: '0644'
      notify: restart mysql

    - name: Configure MySQL for GTID replication
      lineinfile:
        path: /etc/my.cnf
        line: "{{ item }}"
        create: yes
      loop:
        - gtid_mode=ON
        - enforce-gtid-consistency=ON
        - log_bin=binlog
        - binlog_format=row
        - server_id=1
      notify: restart mysql

    - name: Start MySQL service
      systemd:
        name: mysql
        state: started
        enabled: yes

    - name: Get the autogenerated MySQL root password
      command: "grep 'root@localhost:' /var/log/mysqld.log | awk '{print $11}'"
      register: mysql_root_auto_password
      changed_when: false

    - name: Change MySQL root password
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_auto_password.stdout }}"
        name: root
        password: "{{ mysql_root_password }}"
        host: localhost
        state: present

    - name: Create replication user
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: "{{ replication_user }}"
        password: "{{ replication_password }}"
        host: '%'
        priv: '*.*:REPLICATION SLAVE'
        state: present

    - name: Import database dump
      mysql_db:
        name: bet
        state: import
        target: "{{ dump_file }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"

  handlers:
    - name: restart mysql
      systemd:
        name: mysql
        state: restarted