---
- name: Setup MySQL Slave with GTID Replication
  hosts: mysql_slave
  become: yes
  vars:
    mysql_root_password: "YourStrongPassword"  # Установите здесь ваш пароль для root
    master_host: "master_ip_address"  # Установите IP-адрес мастера
    replication_user: "repl_user"
    replication_password: "repl_password"

  tasks:
    - name: Install Percona repository
      yum:
        name: "http://www.percona.com/downloads/percona-release/redhat/0.1-6/percona-release-0.1-6.noarch.rpm"
        state: present

    - name: Install Percona Server
      yum:
        name: Percona-Server-server-57
        state: present

    - name: Configure MySQL for GTID replication
      lineinfile:
        path: /etc/my.cnf
        line: "{{ item }}"
        create: yes
      loop:
        - gtid_mode=ON
        - enforce-gtid-consistency=ON
        - log_bin=binlog
        - binlog_format=row
        - server_id=2
      notify: restart mysql

    - name: Start MySQL service
      systemd:
        name: mysql
        state: started
        enabled: yes

    - name: Get the autogenerated MySQL root password
      command: "grep 'root@localhost:' /var/log/mysqld.log | awk '{print $11}'"
      register: mysql_root_auto_password
      changed_when: false

    - name: Change MySQL root password
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_auto_password.stdout }}"
        name: root
        password: "{{ mysql_root_password }}"
        host: localhost
        state: present

    - name: Configure replication settings
      mysql_replication:
        mode: slave
        master_host: "{{ master_host }}"
        master_user: "{{ replication_user }}"
        master_password: "{{ replication_password }}"
        gtid_mode: ON
        state: present